const services = [
  "Web Development & Design",
  "Mobile App Development",
  "Software Development",
  "Cloud Services",
  "Cyber Security",
  "Managed IT Services",
  "Data Analytics And Business",
  "Digital Marketing",
  "E-Commerce Solutions",
  "UI/UX Design",
  "IOT Solutions",
  "Training And Workshops",
  "Graphic Design",
  "Animation Services",
  "Bookkeeping & Acc. Service",
  "Business Consultation",
  "Brand Development",
  "Website Development",
  "Content Creation",
  "Digital Marketing Strategy",
  "Social Media Setup & Management",
  "Search Engine Optimization",
  "Startup Support",
  "Email Management",
  "Calender Management",
  "Real Estate Virtual Assistant",
  "Document Management",
  "Data Entry & Database",
  "Customer Support",
  "Personal Virtual Assistant",
  "Social Media Management",
  "Research & Analysis",
  "Task Coordination",
  "Email Marketing Support",
  "Bookkeeping & Accounting",
  "Event Planning & Coordination",
  "Travel Planning & Coordination",
  "Language Translation",
  "Content Creation & Editing",
  "Transcription Service",
  "Project Management",
  "DataBase Cleanup & Entry",
  "Technical Support & Troubleshooting",
  "Web Development",
  "Data Science & Analytics",
  "Cybesecurity & IT Security",
  "Cloud Computing & Devops",
  "IT Project Management",
  "IT Support & Infrastructure",
  "Administration & Office Support",
  "Finance & Accounting",
  "Retail & Hospitality",
  "Human Resource",
  "Customer Service & Support",
  "Sales & Marketing",
  "Healthcare & Life Sciences",
  "Operations & Supply Management",
  "Technical Support",
  "Order Management",
  "Help Desk Service",
  "Outbound Call Center Service",
  "Appointment Setting",
  "Market Research & Surveys",
  "BackOffice BPO Services",
  "Document Management",
  "Finance & Accounting Outsourcing",
  "HR Outsourcing",
  "Patient Registration & Eligibility Ver.",
  "Medical Coding & Documentation",
  "Denials Management & Appeals",
  "Claims Management & Follow-Up",
  "Payment Posting & Reconcillation",
  "Account Receivable Management",
  "Charge Capture & Claims Sub.",
];

export default services;
